[package]
name = "real-world-axum-sqlx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.5"
tokio = { version = "1.36.0", features = ["full"] }
tower = "0.4.13"
serde = { version = "1.0.197", features = ["derive"] }
anyhow = "=1.0.81"
dotenv = "0.15.0"
argon2 = "0.5.3"


jsonwebtoken = "9.3.0"
log = "0.4.21"